DROP USER IF EXISTS someuser;
CREATE USER SOMEUSER WITH UNENCRYPTED PASSWORD 'somepassword';
DROP DATABASE IF EXISTS protaskm;
CREATE DATABASE protaskm with ENCODING='utf-8' owner=someuser CONNECTION LIMIT=25;